app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),unique = True)
    pass_secure = db.Column(db.String(255))
    comment = db.relationship('Comments',backref='user',lazy='dynamic')
    post = db.relationship('Post',backref='user',lazy='dynamic')
    email=db.Column(db.String(255),unique = True)

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)


    def __repr__(self):
        return f'User {self.username}'

class Post(db.Model):
    __tablename__='posts'
    id=db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String(255))
    category = db.Column(db.String(255))
    description = db.Column(db.String(255))
    comment = db.relationship('Comments',backref='post',lazy='dynamic')
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    def save(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_posts(id):
        posts = Post.query.order_by(post_id = id).desc().all()
        return posts
    
    def __repr__(self):
        return f'Post {self.category}'

class Comments(db.Model):
    __tablename__='comments'
    id=db.Column(db.Integer,primary_key=True)
    comment=db.Column(db.String(255))
    user_id=db.Column(db.Integer,db.ForeignKey('users.id'))
    post_id=db.Column(db.Integer,db.ForeignKey('posts.id'))
    def save(self):
        db.session.add(self)
        db.session.commit()
    def __repr__(self):
        return f'Comments {self.comment}'


class Quotes:
    '''
    Quotes class to define quotes Objects
    '''
    def __init__(self,author,id,quote,permalink):
        self.id = id
        self.title = title
        self.quote = quote
        self.permalink = 'http://quotes.stormconsultancy.co.uk/quotes/25'

app/__init__.py
from flask import Flask
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bootstrap import Bootstrap

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
bootstrap = Bootstrap()

db = SQLAlchemy()
def create_app(config_name):
    app=Flask(__name__)
    app.config.from_object(config_options[config_name])
    from app.main import main as main_blueprint 
    app.register_blueprint(main_blueprint)
    from app.auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
    db.init_app(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import errors , views

app/main/views.py
from flask import render_template,redirect,url_for
from ..requests import get_quotes
from . import main
from flask_login import login_required,current_user
from ..import db
from app.models import Post,Comments
from .form import PostForm,CommentForm

# Views
@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''
    quotes = get_quotes()
    print(quotes)
    # title = 'Home - this is my blog page'
    all_posts = Post.query.all()

    return render_template('index.html',quotes=quotes,all_posts=all_posts)

@main.route('/blog/new/<int:blog_id>', methods = ['GET','POST'])
@login_required
def new_blog(blog_id):
    '''
    View blog page function that returns the blog details page and its data
    '''
    return render_template(blog.html,id = blog_id)

@main.route('/posts/new',methods = ['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        user_id = current_user._get_current_object().id
        post = Post(category= form.category.data,title=form.title.data,description=form.description.data,user_id=user_id)
        post.save()
        return redirect(url_for('main.index'))
    return render_template('post.html',form=form)

@main.route('/comments/<int:post_id>',methods = ['GET','POST'])
@login_required
def comment(post_id):
    forms = CommentForm()
    comments = Comments.query.filter_by(post_id=post_id).all()
    if forms.validate_on_submit():
        post_id = post_id 
        user_id= current_user._get_current_object().id
        comment = Comments(comment=forms.comment.data,user_id=user_id,post_id=post_id)
        comment.save()
        return redirect(url_for('main.index'))
    
    return render_template('comments.html',forms= forms,comments=comments)

app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> This is my Blog </title>
        {% endif %}

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </head>
    <body>
        <!-- Content block -->
        {% block navbar %}
            {% include 'navbar.html' %}
        {% endblock %}
        {% block content %}

        {% endblock%}
    </body>
</html>

app/templates/comments.html
{% extends 'base.html'%}

{% block content %}
<link rel="stylesheet" href="{{url_for('static',filename='styles.css')}}">
<div class="container-fluid" style="padding-bottom:10%"> 
    <div class="container" style="padding-top:10%">
        <div class="row">
          <div class= "col-md-2"> </div>
          <div class="col-md-8">
              <h3> Drop Comment </h3>
          <!--Flash message -->
          <form method="POST" action="">

                {{ forms.csrf_token }}

                <div class="form-group meme">
                    {{ forms.comment.label(class="form-control-label") }}
                    {% if forms.comment.errors %}
                        {{ forms.comment(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in forms.comment.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ forms.comment(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group" style=" color:black;padding-left:30%;padding-right:30%">
                    
                        {{ forms.submit(class="form-control form-control-lg") }}
                
                </div>
            <p> You don't have an account? <a href="{{url_for('auth.create_account')}}">Sign up </a></p>
        </form>    
        </div>
            <div clas="col-md-2"> 
                <h4 style="color:white"> Your comment</h4> 
                {%for comment in comments%}
                    {{comment.comment}}
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock%}

app/templates/index.html
{% extends 'base.html' %}
{% block content %}
<link rel="stylesheet" href="{{url_for('static',filename='styles.css')}}">

        <!-- Quotes section -->    
        <div class="container-fluid" >
                <h3> Daily Quotes </h3> <hr>
                <div class="container duet" >
                        <p style="padding-left:20%; padding-right:20%">                
                                <p>{{ quotes.title }}</p>
                                <p>{{ quotes.quote }}</p>
                                <p>{{quotes.author}}</p>
                        
                        </p>
                <h3>Current Quotes</h3> <hr>
                 {% for post in all_posts %}
                 <div class="post" style=" color:black;padding-left:25%;padding-right:25%">

                 <div class="card">

                         <div class="card-header">
                                 <h2>{{post.category}}</h2>
                         </div> <hr>
                         <div class="card-body">
                                   <p class="card-title">{{post.title}}</p>
                                   <p class="card-text">{{post.description}}</p>
                                   <a href="{{url_for('main.comment', post_id = post.id)}}" class="btn btn-primary">Comment</a>
                         </div>
                 </div>
                 </div> <br>
                 {% endfor %}
                </div>   

                
        </div>    

{% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
        <a class="navbar-brand" href="{{url_for('main.index')}}">Home</a>
        <a class="navbar-brand" href="{{url_for('main.new_post')}}">Post</a> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
        &nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
          <a href="{{url_for('auth.create_account')}}" style="background-color:aliceblue"><span class="glyphicon glyphicon-user"></span> Sign Up</a>  &nbsp; &nbsp; &nbsp; &nbsp;
          <a href="{{url_for('auth.login')}}" style="background-color:aliceblue"><span class="glyphicon glyphicon-log-in"></span> Login</a>  
      </div>
    </div>
  </nav>

app/templates/post.html
{% extends 'base.html' %}
{% block content %}
<link rel="stylesheet" href="{{url_for('static',filename='styles.css')}}">

<div class="container-fluid" style="padding-left:20%; padding-right:20%;padding-bottom:13%">
<div class="container">
<h3>Post here</h3> <hr>
<form method="POST" action="">

        {{ form.csrf_token }}

        <div class="form-group meme">
            {{ form.title.label(class="form-control-label") }}
            {% if form.title.errors %}
                {{ form.title(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.title(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        

        <div class="form-group">
            {{ form.description.label(class="form-control-label") }}
            {% if form.description.errors %}
                {{ form.description(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.description.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.description(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.category.label(class="form-control-label") }}
            {% if form.category.errors %}
                {{ form.category(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.category.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.category(class="form-control form-control-lg") }}
            {% endif %}
        </div>

        <div class="form-group" style=" color:black;padding-left:30%;padding-right:30%">
            
                {{ form.submit(class="form-control form-control-lg") }}
        
        </div>
</form> 
</div>

</div>

{% endblock %}